spring.application.name=ms-context-builder
server.port=8080
servlet.context-path=/context-builder

# MongoDB
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=mydatabase
spring.mongodb.username=admin
spring.mongodb.password=admin
spring.data.mongodb.host=${spring.mongodb.host}
spring.data.mongodb.port=${spring.mongodb.port}
spring.data.mongodb.database=${spring.mongodb.database}
spring.data.mongodb.username=${spring.mongodb.username}
spring.data.mongodb.password=${spring.mongodb.password}

# AI RestClient
ai-index.client.base-url=http://localhost:8081/ai-engine/api
