spring.application.name=ms-dev-mentor

# === MongoDB ===
spring.data.mongodb.uri=mongodb://admin:admin@localhost:27017/ms_dev_mentor?authSource=admin

# === AI Index RestClient ===
ai-index.client.base-url=http://localhost:8081
